<nav class="navbar navbar-expand-lg navbar-light shadow">
  <a class="navbar-brand text-light" href="#">Barcelos and Will Portfolio |</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link text-light" href="#"> Sobre nós </a>
        </li>
        
        <li class="nav-item active ">
          <a class="nav-link text-light" href="#"> Contato </a>
        </li>
      </ul>
      <ul class="navbar-nav justify-content-end mr-0">
          <li class="nav-item active float-right">
          
          <button style="color:#530303" type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal">
            Login
          </button>
          </li>
      </ul> 
  </div>

</nav>
          
    <!--carrossel -->

<div class="container"><!--Container -->
  <div class="row"><!--Row -->
    <div class="col-sm-8 m-auto"><!--col-sm8 -->
      
      <div id="carousel-indicadores" class="carousel slide" data-ride="carousel"><!--Carousel -->

        <!-- Indicadores -->
        <ol class="carousel-indicators">
      
          <li class="active" data-target="#carousel-indicadores" data-slide-to="0"></li>
      
          <li data-target="#carousel-indicadores" data-slide-to="1"></li>
      
          <li data-target="#carousel-indicadores" data-slide-to="2"></li>
      
        </ol>
      
        <div class="carousel-inner"><!--Inner -->
          
          <div class="carousel-item active">
            <img src="./images/1.jpg" class="img-fluid">
          </div>
      
          <div class="carousel-item">
            <img src="./images/2.jpg" class="img-fluid">
          </div>
      
          <div class="carousel-item">
            <img src="./images/3.jpg" class="img-fluid">
          </div>
      
        </div><!--/Inner -->
      
        <!-- Controles -->
        <a href="#carousel-indicadores" class="carousel-control-prev" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
      
        <a href="#carousel-indicadores" class="carousel-control-next" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      
      </div>
      
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title m-auto" id="exampleModalLabel">Área administrativa</div>
        </button>
      </div>
      <div class="modal-body">



        <form action="/autenticar" method="POST">
          <div class="form-group">
            <label for="exampleInputEmail1">Login</label>
            <input name="login" type="text" class="form-control" placeholder="Enter login">
            <small class="form-text text-muted">This is edit area only. For contact, mail us.</small>
          </div>
          <div class="form-group">
            <label>Password</label>
            <input name="senha" type="password" class="form-control" placeholder="Password">
          </div>
        

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-info">Entrar</button>
      </form>
      </div>


    </div>
  </div>
</div>