      <!--carrossel -->

<div class="container"><!--Container -->
  <div class="row"><!--Row -->
    <div class="col-sm-8 m-auto"><!--col-sm8 -->
      
      <div id="carousel-indicadores" class="carousel slide" data-ride="carousel"><!--Carousel -->

        <!-- Indicadores -->
        <ol class="carousel-indicators">
      
          <li class="active" data-target="#carousel-indicadores" data-slide-to="0"></li>
      
          <li data-target="#carousel-indicadores" data-slide-to="1"></li>
      
          <li data-target="#carousel-indicadores" data-slide-to="2"></li>
      
        </ol>
      
        <div class="carousel-inner"><!--Inner -->
          
          <div class="carousel-item active">
            <img src="./images/1.jpg" class="img-fluid">
          </div>
      
          <div class="carousel-item">
            <img src="./images/2.jpg" class="img-fluid">
          </div>
      
          <div class="carousel-item">
            <img src="./images/3.jpg" class="img-fluid">
          </div>
      
        </div><!--/Inner -->
      
        <!-- Controles -->
        <a href="#carousel-indicadores" class="carousel-control-prev" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
      
        <a href="#carousel-indicadores" class="carousel-control-next" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      
      </div>
      
    </div>
  </div>
</div>


